/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <sstream>

#include <boost/test/unit_test.hpp>

#include "../SourceFileGenerator.h"

#include "version.h"

using namespace apache::thrift::compiler::generate::cpp_v2;
using namespace apache::thrift::compiler::generate;

namespace {

struct SourceGeneratorFixture {
  std::ostringstream stream;
};

class ContentsGeneratorStub : public ContentsGenerator {
public:
  ContentsGeneratorStub(OutputGenerator& parent,
                        const std::string& text,
                        const std::string& include)
    : ContentsGenerator(parent), text_(text), include_(include) {}

  void generateContents() override { out() << text_ << endl; }

  void generateHeader() override { out() << "#include <" << include_ << ">" << endl; }

private:
  const std::string text_;
  const std::string include_;
};

BOOST_FIXTURE_TEST_SUITE(SourceGeneratorTests, SourceGeneratorFixture)

BOOST_AUTO_TEST_CASE(SourceGenerator_constructs_from_stream_and_is_OutputGenerator) {
  SourceFileGenerator gen(stream, "module", "namespace_name");
  BOOST_CHECK(dynamic_cast<OutputGenerator*>(&gen));
}

BOOST_AUTO_TEST_CASE(SourceGenerator_provides_proper_source_contents) {
  SourceFileGenerator gen(stream, "module", "module_namespace");
  gen.generate<ContentsGeneratorStub>("dummy contents", "header.h");

  BOOST_CHECK_EQUAL(stream.str(),
                    "/**\n"
                    " * Autogenerated by Thrift Compiler (" THRIFT_VERSION
                    ")\n"
                    " *\n"
                    " * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n"
                    " *  @generated\n"
                    " */\n"
                    "\n"
                    "#include \"module.h\"\n"
                    "\n"
                    "#include <header.h>\n"
                    "\n"
                    "namespace module_namespace {\n"
                    "\n"
                    "dummy contents\n"
                    "\n"
                    "} // namespace module_namespace\n");
}

BOOST_AUTO_TEST_CASE(SourceGenerator_supports_empty_namespace) {
  SourceFileGenerator gen(stream, "module", "");
  gen.generate<ContentsGeneratorStub>("dummy contents", "header.h");

  BOOST_CHECK_EQUAL(stream.str(),
                    "/**\n"
                    " * Autogenerated by Thrift Compiler (" THRIFT_VERSION
                    ")\n"
                    " *\n"
                    " * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n"
                    " *  @generated\n"
                    " */\n"
                    "\n"
                    "#include \"module.h\"\n"
                    "\n"
                    "#include <header.h>\n"
                    "\n"
                    "dummy contents\n");
}

BOOST_AUTO_TEST_CASE(SourceGenerator_provides_proper_source_contents_for_different_params) {
  SourceFileGenerator gen(stream, "module2", "module.module2");
  gen.generate<ContentsGeneratorStub>("other dummy contents", "header2.h");

  BOOST_CHECK_EQUAL(stream.str(),
                    "/**\n"
                    " * Autogenerated by Thrift Compiler (" THRIFT_VERSION
                    ")\n"
                    " *\n"
                    " * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING\n"
                    " *  @generated\n"
                    " */\n"
                    "\n"
                    "#include \"module2.h\"\n"
                    "\n"
                    "#include <header2.h>\n"
                    "\n"
                    "namespace module { namespace module2 {\n"
                    "\n"
                    "other dummy contents\n"
                    "\n"
                    "}} // namespace module::module2\n");
}

BOOST_AUTO_TEST_SUITE_END()

} // namespace
